// Generated by CoffeeScript 1.12.7
(function() {
  var Saimaa, SaimaaDOM, SaimaaUtil;

  SaimaaUtil = require("./saimaa_util");

  SaimaaDOM = require("./saimaa_dom");

  Saimaa = (function() {
    function Saimaa(source) {
      this.source = source;
      this.initEditor();
      this.dom = new SaimaaDOM(this.editor);
      this.editor.addEventListener("keydown", (function(_this) {
        return function(event) {
          return _this.onKeyDown(event);
        };
      })(this));
      this.editor.addEventListener("keyup", (function(_this) {
        return function(event) {
          return _this.onKeyUp(event);
        };
      })(this));
    }

    Saimaa.prototype.initEditor = function() {
      this.editor = document.createElement("div");
      this.editor.contentEditable = true;
      this.editor.className = this.source.className;
      this.source.parentNode.insertBefore(this.editor, this.source);
      return this.source.style.display = "none";
    };

    Saimaa.prototype.onKeyDown = function(event) {
      if (this.editor.children.length === 0) {
        return this.dom.formatBlock("p");
      } else {
        if (event.keyCode === 13) {
          return "aaa";
        }
      }
    };

    Saimaa.prototype.onKeyUp = function(event) {
      return "bar";
    };

    return Saimaa;

  })();

  module.exports = Saimaa;

}).call(this);
