// Generated by CoffeeScript 1.12.7
(function() {
  var SaimaaDOM, SaimaaUtil, h;

  h = require("h");

  SaimaaUtil = require("./saimaa_util");

  SaimaaDOM = (function() {
    function SaimaaDOM(editor) {
      this.editor = editor;
      this.lastNode = null;
    }

    SaimaaDOM.prototype.html = function() {
      return this.editor.innerHTML;
    };

    SaimaaDOM.prototype.caretNode = function() {
      var node, result;
      node = window.getSelection().anchorNode;
      if ((node != null) && node.nodeType === Node.TEXT_NODE || ((node.tagName != null) && node.tagName === "BR")) {
        result = node.parentNode;
      } else {
        result = node;
      }
      return result;
    };

    SaimaaDOM.prototype.add = function(node) {
      var range, selection;
      selection = window.getSelection();
      if (selection.rangeCount > 0) {
        range = selection.getRangeAt(0);
        console.log("anchor", selection.anchorNode, "start", range.startContainer, range.startOffset, "end", range.endContainer, range.endOffset);
        range.insertNode(node);
        range.setStartAfter(node);
        return range.collapse(true);
      }
    };

    SaimaaDOM.prototype.addBr = function() {
      var br, br2, range, selection;
      selection = window.getSelection();
      if (selection.rangeCount > 0) {
        range = selection.getRangeAt(0);
        br = h("br");
        br2 = h("br");
        range.insertNode(br);
        range.insertNode(br2);
        range.setStartAfter(br2);
        return range.collapse(true);
      }
    };

    SaimaaDOM.prototype.append = function(node) {
      if (this.editor === this.caretNode()) {
        this.editor.appendChild(node);
      } else {
        this.editor.insertBefore(node, this.caretNode().nextSibling);
      }
      return this.moveCaret(node);
    };

    SaimaaDOM.prototype.appendP = function() {
      var br, p;
      p = h("p");
      br = h("br");
      p.appendChild(br);
      return this.append(p);
    };

    SaimaaDOM.prototype.appendLi = function() {
      var li;
      li = document.createElement("li");
      li.appendChild(document.createElement("br"));
      return this.append(li);
    };

    SaimaaDOM.prototype.changeTag = function(tag) {
      var childNode, i, len, newNode, oldCaretNode, ref;
      newNode = h(tag);
      oldCaretNode = this.caretNode();
      ref = oldCaretNode.childNodes;
      for (i = 0, len = ref.length; i < len; i++) {
        childNode = ref[i];
        newNode.appendChild(childNode);
      }
      this.append(newNode);
      this.moveCaret(newNode);
      return this.editor.removeChild(oldCaretNode);
    };

    SaimaaDOM.prototype.changeList = function(tag) {
      var br, li, list, oldCaretNode;
      if (this.lastNode) {
        this.moveCaret(this.lastNode);
      }
      oldCaretNode = this.caretNode();
      list = h(tag);
      li = h("li");
      br = h("br");
      li.appendChild(br);
      list.appendChild(li);
      this.append(list);
      this.moveCaret(br);
      if (this.editor !== oldCaretNode) {
        return this.editor.removeChild(oldCaretNode);
      }
    };

    SaimaaDOM.prototype.changeUl = function() {
      return this.changeList("ul");
    };

    SaimaaDOM.prototype.changeOl = function() {
      return this.changeList("ol");
    };

    SaimaaDOM.prototype.changeH2 = function() {
      return this.changeTag("h2");
    };

    SaimaaDOM.prototype.changeH3 = function() {
      return this.changeTag("h3");
    };

    SaimaaDOM.prototype.changeH4 = function() {
      return this.changeTag("h4");
    };

    SaimaaDOM.prototype.changeBlockquote = function() {
      var bq, childNodes, i, lastNode, len, node;
      if (this.lastNode) {
        this.moveCaret(this.lastNode);
      }
      childNodes = this.caretNode().childNodes;
      lastNode = childNodes;
      bq = h("blockquote");
      for (i = 0, len = childNodes.length; i < len; i++) {
        node = childNodes[i];
        bq.appendChild(node);
      }
      return this.append(bq);
    };

    SaimaaDOM.prototype.changeTitle = function() {
      return this.editor.childNodes[0].className = "title";
    };

    SaimaaDOM.prototype.formatBlock = function(tag) {
      var t;
      if (this.lastNode) {
        this.moveCaret(this.lastNode);
      }
      if (SaimaaUtil.ie()) {
        t = "<" + tag + ">";
      } else {
        t = tag;
      }
      return document.execCommand("formatBlock", false, t);
    };

    SaimaaDOM.prototype.afterDoubleBr = function() {
      var range;
      this.caretNode().normalize();
      range = window.getSelection().getRangeAt(0);
      console.log("start", range.startContainer, range.startOffset);
      return false;
    };

    SaimaaDOM.prototype.inLi = function() {
      return this.caretNode().tagName.toLowerCase() === "li";
    };

    SaimaaDOM.prototype.inP = function() {
      return this.caretNode().tagName.toLowerCase() === "p";
    };

    SaimaaDOM.prototype.inTitle = function() {
      return this.caretNode().className.toLowerCase() === "title";
    };

    SaimaaDOM.prototype.moveCaret = function(node) {
      var range, selection;
      range = document.createRange();
      selection = window.getSelection();
      range.setStart(node, 0);
      range.collapse(true);
      selection.removeAllRanges();
      return selection.addRange(range);
    };

    SaimaaDOM.prototype.saveLastNode = function() {
      if (this.editor !== this.caretNode() && this.editor.contains(this.caretNode())) {
        return this.lastNode = this.caretNode();
      }
    };

    return SaimaaDOM;

  })();

  module.exports = SaimaaDOM;

}).call(this);
