// Generated by CoffeeScript 1.12.7
(function() {
  var SaimaaUI;

  SaimaaUI = (function() {
    function SaimaaUI() {}

    SaimaaUI.prototype.name = function() {
      return "bar";
    };

    return SaimaaUI;

  })();

  module.exports = SaimaaUI;

}).call(this);
