// Generated by CoffeeScript 1.12.7
(function() {
  var SaimaaUI, h;

  h = require("h");

  SaimaaUI = (function() {
    function SaimaaUI(editor) {
      this.editor = editor;
      this.createBlockUI();
      this.createSelectionUI();
    }

    SaimaaUI.prototype.createBlockUI = function() {
      this.blockUI = h("div.saimaa-block-ui", {
        style: "display: none"
      });
      this.h2 = h("div.saimaa-block-ui__action.is-h2", "H2");
      this.blockUI.appendChild(this.h2);
      this.h3 = h("div.saimaa-block-ui__action.is-h3", "H3");
      this.blockUI.appendChild(this.h3);
      this.h4 = h("div.saimaa-block-ui__action.is-h4", "H4");
      this.blockUI.appendChild(this.h4);
      this.ol = h("div.saimaa-block-ui__action.is-ol", "OL");
      this.blockUI.appendChild(this.ol);
      this.ul = h("div.saimaa-block-ui__action.is-ul", "UL");
      this.blockUI.appendChild(this.ul);
      this.bq = h("div.saimaa-block-ui__action.is-bq", "BQ");
      this.blockUI.appendChild(this.bq);
      this.clear = h("div.saimaa-block-ui__action.is-clear", "CLEAR");
      this.blockUI.appendChild(this.clear);
      return this.editor.parentNode.insertBefore(this.blockUI, this.editor.nextSibling);
    };

    SaimaaUI.prototype.createSelectionUI = function() {
      this.selectionUI = h("div.saimaa-selection-ui", {
        style: "display: none"
      });
      this.strong = h("div.saimaa-selection-ui__action", "B");
      this.selectionUI.appendChild(this.strong);
      this.em = h("div.saimaa-selection-ui__action", "EM");
      this.selectionUI.appendChild(this.em);
      this.strike = h("div.saimaa-selection-ui__action", "S");
      this.selectionUI.appendChild(this.strike);
      this.linkText = h("input#link_text.saimaa-selection-ui__action");
      this.linkText.type = "text";
      this.selectionUI.appendChild(this.linkText);
      this.link = h("div#link.saimaa-selection-ui__action", "LINK");
      this.selectionUI.appendChild(this.link);
      return this.editor.parentNode.insertBefore(this.selectionUI, this.editor.nextSibling);
    };

    return SaimaaUI;

  })();

  module.exports = SaimaaUI;

}).call(this);
