// Generated by CoffeeScript 1.12.7
(function() {
  var SaimaaUI, h;

  h = require("h");

  SaimaaUI = (function() {
    function SaimaaUI(editor) {
      this.editor = editor;
      this.createBlockUI();
      this.createSelectUI();
    }

    SaimaaUI.prototype.createBlockUI = function() {
      this.blockUI = h("div.saimaa-block-ui", {
        style: "display: block"
      });
      this.h2 = h("div.saimaa-block-ui__action.is-h2", "H2");
      this.blockUI.appendChild(this.h2);
      this.h3 = h("div.saimaa-block-ui__action.is-h3", "H3");
      this.blockUI.appendChild(this.h3);
      this.h4 = h("div.saimaa-block-ui__action.is-h4", "H4");
      this.blockUI.appendChild(this.h4);
      this.ol = h("div.saimaa-block-ui__action.is-ol", "OL");
      this.blockUI.appendChild(this.ol);
      this.ul = h("div.saimaa-block-ui__action.is-ul", "UL");
      this.blockUI.appendChild(this.ul);
      this.bq = h("div.saimaa-block-ui__action.is-bq", "BQ");
      this.blockUI.appendChild(this.bq);
      this.clear = h("div.saimaa-block-ui__action.is-clear", "CLEAR");
      this.blockUI.appendChild(this.clear);
      return this.editor.parentNode.insertBefore(this.blockUI, this.editor.nextSibling);
    };

    SaimaaUI.prototype.createSelectUI = function() {
      this.selectUI = h("div.saimaa-select-ui", {
        style: "display: block"
      });
      return this.editor.parentNode.insertBefore(this.selectUI, this.editor.nextSibling);
    };

    return SaimaaUI;

  })();

  module.exports = SaimaaUI;

}).call(this);
